name: Multiple Architecture Image Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release-*'
    tags:
      - 'v*'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image-build:
    uses: konveyor/release-tools/.github/workflows/build-push-images.yaml@main
    with:
      registry: "quay.io/carlosthe19916"
      image_name: "guac-ui"
      containerfile: "./Containerfile"
      architectures: '[ "amd64", "arm64" ]'
      extra-args: "--ulimit nofile=4096:4096"
      pre_build_cmd: |
        sed -i '/RUN npm clean-install/i RUN npm install -g npm@9' Containerfile
    secrets:
      registry_username: ${{ secrets.QUAY_PUBLISH_ROBOT }}
      registry_password: ${{ secrets.QUAY_PUBLISH_TOKEN }}
